config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'drinkings#index'
  get  "drinkings/index_admin_user/:id"  => "drinkings#index_admin_user", as:"index_admin_user"


  resources :drinkings do
    collection do
      get :calculation 
      get :index_admin_day
    end
  end

  resources :visuallies
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
end

app/models/drinking.rb
class Drinking < ApplicationRecord  
  enum status: {未入力:0, 〇:1, ×:2}

  belongs_to :user
  has_many :alcohols, dependent: :destroy
  has_many :visuallies, dependent: :destroy

  accepts_nested_attributes_for :alcohols, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :visuallies, reject_if: :all_blank, allow_destroy: true

  validates_associated :alcohols
  validates :alcohols, presence: true, if: -> { status == "〇" }
  
  def total_alcohol
    alcohols.to_a.sum { |alcohol| alcohol.quantity * alcohol.frequency * alcohol.number / 100 * 0.8 }
  end

  def time
    drinking_end_time + (total_alcohol / user.weight / 0.1).hour
  end
end

app/controllers/drinkings_controller.rb
class DrinkingsController < ApplicationController
  before_action :set_drinking, only: %i[ show edit update destroy ]
  before_action :require_admin, only: %i[ index_admin_day index_admin_user ]

  # GET /drinkings or /drinkings.json
  def index
    @month = params[:month] ? Date.parse(params[:month]) : Time.zone.today    
    @drinkings = Drinking.left_outer_joins(:user).includes(:visuallies).where(users: {id: current_user.id}).where(driving_start_time: @month.all_month).order("driving_start_time")
  end

  def index_admin_day
    @day = params[:day] ? Date.parse(params[:day]) : Time.zone.today   
    @q = Drinking.left_outer_joins(:visuallies).where(driving_start_time: @day.all_day).ransack(params[:q])
    @drinkings = @q.result(distinct: true)
  end

  def index_admin_user
    @user = User.find(params[:id])
    @month = params[:month] ? Date.parse(params[:month]) : Time.zone.today    
    @r = @user.drinkings.where(driving_start_time: @month.all_month).ransack(params[:q])
    @drinkings = @r.result(distinct: true)
  end

  # GET /drinkings/1 or /drinkings/1.json
  def show
  end

  # GET /drinkings/new
  def new
    @drinking = Drinking.new
    @drinking.alcohols.build
    @drinking.visuallies.build
  end

  # GET /drinkings/1/edit
  def edit
  end

  # POST /drinkings or /drinkings.json
  def create
    @user = current_user
    @drinking = current_user.drinkings.new(drinking_params)

    if @drinking.save
      @user.drinkings << @drinking
      redirect_to drinkings_path(current_user.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /drinkings/1 or /drinkings/1.json
  def update
    if @drinking.update(drinking_params)
      flash[:notice] = '飲酒記録を更新しました' 
      redirect_to drinkings_path(current_user.id)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /drinkings/1 or /drinkings/1.json
  def destroy
    @drinking.destroy

    respond_to do |format|
      format.html { redirect_to drinkings_url, notice: "Drinking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def calculation
    @user = current_user
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drinking
      @drinking = Drinking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def drinking_params
      params.require(:drinking).permit(:status, :driving_start_time, :drinking_end_time, :time, :user_id, alcohols_attributes: [:id, :kind, :frequency, :quantity, :number, :_destroy], visuallies_attributes: [:id, :visually])
    end

    def require_admin
      redirect_to root_path unless current_user.admin?
    end
end

app/helpers/drinkings_helper.rb
module DrinkingsHelper
end

app/views/drinkings/_alcohol.html.erb
<div class="nested-fields">
  <div class="fields">
    <div class="field">
      <%= alcohol.label :種類 %>
      <%= alcohol.text_field :kind,:size=>"10" %>
    </div>

    <div class="field">
      <%= alcohol.label :度数 %>
      <%= alcohol.number_field :frequency, step: "0.1", min: 0, max: 100 %>
    </div>


    <div class="field">
      <%= alcohol.label :量（ml） %>
      <%= alcohol.number_field :quantity, min: 0, max: 999 %>
    </div>

    <div class="field">
      <%= alcohol.label :本数 %>
      <%= alcohol.number_field :number, step: "0.1", min: 0, max: 100 %>
    </div>
  </div>

    <div class="field">
      <%= link_to_remove_association "-お酒入力フォーム削除", alcohol %>
    </div>
    <hr>
</div>

app/views/drinkings/calculation.html.erb
<section class="section">
  <div class ="section_inner">
    <h1>飲酒量計算</h1>

    <h4 id="error_message"></h4>

    <form name="calculation" id="calculation">
      <div class="input-form">
        <div class="form" id="driving_start_time">
          <label>運転日時</label>
          <input type="datetime-local" id="driving_time">
        </div>

        <div class="form" id="driking_end_time">
          <label>飲酒日時</label>
          <input type="datetime-local" id="drinking_time">
        </div>
      </div>

      <input type="hidden" id="user_weight"  value="<%= @user.weight %>">

      <div class="button">
        <input type="button" value="計算" onclick="calc(driving_start_time);" class="btn">
        <input type="button" value="リセット" onclick="reSet(driving_start_time);" class="btn">
      </div>
    </form>

    <hr color="#f5b771">

    <h3>選択時間からの飲酒可能量</h3>
    
    <div class="calc-result">
      <label class="label">ビール（500ml）なら</label>
      <div>
        <input type="textarea" readonly="" id="beer" value=0 size=3>杯
      </div>
    </div>
    <div class="calc-result">
      <label class="label">日本酒（180ml）なら</label>
      <div>
        <input type="textarea" readonly="" id="sake" value=0 size=3>合
      </div>
    </div>
    <div class="calc-result">
      <label class="label">ウイスキー（60ml）なら</label>
      <div>
        <input type="textarea" readonly="" id="whiskey" value=0 size=3>杯
      </div>
    </div>
    <div class="calc-result">
      <label class="label">焼酎（25度 100ml）なら</label>
      <div>
        <input type="textarea" readonly="" id="shochu" value=0 size=3>杯
      </div>
    </div>
    <div class="calc-result">
      <label class="label">チューハイ（7% 350ml）なら</label>
      <div>
        <input type="textarea" readonly="" id="chuhai" value=0 size=3>杯
      </div>
    </div>

    <br>※体型やその日の体調によって適量は異なります。
    <br>　適量を守って楽しく飲みましょう！

    <script>
      function calc(driving_start_time) {
        var start_time = document.getElementById("driving_time").valueAsNumber;  
        var drinking_time = document.getElementById("drinking_time").valueAsNumber;  
        var weight = document.getElementById("user_weight").value;
        var weight_num = Number(weight);
        var text = document.getElementById('error_message').textContent;
    
        if (start_time - drinking_time >= 0){
          //エラーメッセージ削除
          document.getElementById('error_message').textContent = '';

          //度数×量（ml）
          var time_diff = start_time - drinking_time;
          var alcohol = time_diff * weight_num / 288000;

          //ビールの場合
          var beer = Math.round(alcohol / 2500 * 10) / 10;
          var beerForm = document.getElementById("beer");
          beerForm.value = beer;

          //日本酒の場合
          var sake = Math.round(alcohol / 2700 *10) / 10;
          var sakeForm = document.getElementById("sake");
          sakeForm.value = sake;

          //ウイスキーの場合
          var whiskey = Math.round(alcohol / 2400 * 10) / 10;
          var whiskeyForm = document.getElementById("whiskey");
          whiskeyForm.value = whiskey;

          //焼酎の場合
          var shochu = Math.round(alcohol / 2500 * 10) / 10;
          var shochuForm = document.getElementById("shochu");
          shochuForm.value = shochu;
   
          //チューハイの場合
          var chuhai = Math.round(alcohol / 2450 * 10) / 10;
          var chuhaiForm = document.getElementById("chuhai");
          chuhaiForm.value = chuhai;

        }else{
          //エラーメッセージ表示
          document.getElementById('error_message').textContent = '運転日時を飲酒日時よりも先の時間を指定してください';
        }
      }

      function reSet(driving_start_time) {
        document.getElementById("beer").value = 0;
        document.getElementById("sake").value = 0;
        document.getElementById("whiskey").value = 0;
        document.getElementById("shochu").value = 0;
        document.getElementById("chuhai").value = 0;
      }
    </script>
  </div>
</section>

app/views/drinkings/edit.html.erb
<section class="section">
  <div class ="section_inner">
    <h1>飲酒記録編集</h1>

    <%= form_with(model: @drinking, local: true) do |form| %>
      <% if @drinking.errors.any? %>
        <div id="error_explanation">
          <h2>エラーが発生しました。</h2>
          <ul>
            <% @drinking.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
  
      <div class="field setting">
        <%= form.label :運転日時 %>
        <%= form.datetime_select :driving_start_time %>
      </div>
  
      <div class="field setting", id="status">
        <span class="status">飲酒状況</span><br>
        <div class ="radio-btn">
          <div class="radio-inline">
            <%= form.label :飲酒, class: "label" %>
            <%= form.radio_button :status, :〇, class: "btn", id: "alcohol_btn" %>
          </div>
          <div class="radio-inline">
            <%= form.label :未飲酒, class: "label" %>
            <%= form.radio_button :status, :× , class: "btn", id: "non_alcohol_btn" %>
          </div>
        </div>
      </div>
   

      <div id="alcohol_format">
        <div class="field setting">
          <%= form.label :飲酒日時 %>
          <%= form.datetime_select :drinking_end_time %>
        </div>

        <hr color="#f5b771">
  
        <div id="alcohol_forms">
          <%= form.fields_for :alcohols do |alcohol| %>
            <% render 'alcohol', alcohol: alcohol %>
          <% end %>
        </div>
        <%= link_to_add_association '+お酒入力フォーム追加', form, :alcohols, partial: "alcohol", data: {association_insertion_node: '#alcohol_forms', association_insertion_method: 'after'}, form_name: 'alcohol' %>
      </div>

      <div class = "button">
        <div class="actions">
          <%= form.submit "登録" %>
        </div>
    <% end %>
  
    <div id = "back">
      <%= link_to '戻る', drinkings_path %>
    </div>
    </div>

    <script>
      var element1 = document.getElementById("alcohol_btn");
      var element2 = document.getElementById("non_alcohol_btn");
  
      element1.addEventListener('click', function() {
        document.getElementById('alcohol_format').style.display = "";
      })
  
      element2.addEventListener('click', function() {
        document.getElementById('alcohol_format').style.display = "none";
      })
    </script>
  </div>
</section>

app/views/drinkings/index.html.erb
<p id="notice"><%= notice %></p>

<section class="section">
<div class ="section_inner">
<h1>飲酒記録一覧（<%= @month.strftime("%m月") %>）</h1>

<% if current_user.weight != nil %>

<%= link_to "前月", drinkings_path(month: @month.prev_month) %>
<%= link_to "翌月", drinkings_path(month: @month.next_month) %>

<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
<% end %>   

<table class="osare3-table col4t">
  <thead>
    <tr>
      <th></th>
      <th>運転日時</th>
      <th>飲酒</th>
      <th>飲酒日時</th>
      <th>運転可能</th>
      <th>目視</th>
      <th>編集</th>
      <th>削除</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drinkings.each do |drinking| %>
      <tr>
        <td>
        <% if (drinking.time - drinking.driving_start_time).to_i > 0 %>
          <%= "警告" %>
        <% end %>
        </td>
        <td><%= drinking.driving_start_time.strftime("%m/%d %H:%M") %></td>
        <td><%= link_to drinking.status, drinking_path(drinking) %></td>
        <td>
        <% if drinking.status == "〇" %>
        <%= drinking.drinking_end_time.strftime("%m/%d %H:%M") %>
        <% end %></td>
        <td>
        <% if (drinking.time - Time.now).to_i >= 0 %>
          <%= drinking.time.strftime("%m/%d %H:%M") %>
        <% else %>
          <%= "〇" %>
        <% end %>
        </td>
        <td><% drinking.visuallies.each do |visually| %>
            <%= visually.visually %>
            <% end %></td>
        <td><%= link_to '編集', edit_drinking_path(drinking) %></td>
        <td><%= link_to '削除', drinking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規作成', new_drinking_path %>
<% else %>
<%= "体重をご入力いただいた場合、ご使用できます。" %>
<% end %>
</div>
</section>

app/views/drinkings/index_admin_day.html.erb
<section class="section">
<div class ="section_inner">
<h1><%=@day.strftime("%Y年%m月%d日") %>　飲酒記録一覧</h1>

<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
<% end %>   

<%= search_form_for @q, url: index_admin_day_drinkings_path do |f| %>
  <div class="search-form">
    <div class="search-form-parts">
      <%= f.label :status_cont, '名前' %>
      <%= f.search_field :user_name_cont %> 
    </div>
    <div class="search-form-parts">
      <%= f.label :status, '飲酒' %>
      <%= f.radio_button :status_eq,"", {:checked => true} %>指定なし
      <%= f.radio_button :status_eq, 1 %>飲酒
      <%= f.radio_button :status_eq, 2 %>未飲酒
    </div>
    <div class="submit">
      <%= f.submit '検索' %>
    </div>
  </div>
<% end %>

<%= link_to "前日", index_admin_day_drinkings_path(day: @day.prev_day, drinkings: @drinkings) %>
<%= link_to "翌日", index_admin_day_drinkings_path(day: @day.next_day) %>

<table class="osare3-table col4t">
  <thead>
    <tr>
      <th></th>
      <th>名前</th>
      <th>運転日時</th>
      <th>飲酒</th>
      <th>飲酒日時</th>
      <th>運転可能</th>
      <th>目視</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drinkings.each do |drinking| %>
      <tr>
      <td>
      <% if (drinking.time - drinking.driving_start_time).to_i > 0 %>
        <%= "警告" %>
      <% end %>
      <% drinking.visuallies.each do |visually| %>
        <% if visually.visually == "未確認" and (drinking.driving_start_time - Time.now).to_i < 0 %>
          <%= "確認" %>
        <% end %>
      <% end %>
      </td>
      <td><%= link_to drinking.user.name, index_admin_user_path(id: drinking.user_id) %></td>
      <td><%= drinking.driving_start_time.strftime("%m/%d %H:%M") %></td>
        <td><%= link_to drinking.status, drinking_path(drinking) %></td>
        <td>
        <% if drinking.status == "〇" %>
        <%= drinking.drinking_end_time.strftime("%m/%d %H:%M") %>
        <% end %></td>
        <td>
        <% if (drinking.time - Time.now).to_i >= 0 %>
          <%= drinking.time.strftime("%m/%d %H:%M") %>
        <% else %>
          <%= "〇" %>
        <% end %>
        </td>
        <td><% drinking.visuallies.each do |visually| %>
          <%= link_to visually.visually, edit_visually_path(visually) %>
        <% end %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
</section>

app/views/drinkings/index_admin_user.html.erb
<p id="notice"><%= notice %></p>

<section class="section">
<div class ="section_inner">
<h1><%= @user.name %>さん　飲酒記録一覧（<%= @month.strftime("%m月") %>）</h1>

<%= search_form_for @r, url: index_admin_user_path do |f| %>
  <div class="search-form search-form-user">
  <div class="search-form-parts">
  <%= f.label :driving_start_time, '運転日' %>
  <%= f.date_field :driving_start_time_gteq %>
  ~
  <%= f.date_field :driving_start_time_lteq %>
  </div>

  <div class="search-form-parts">
  <%= f.label :status, '飲酒' %>
  <%= f.radio_button :status_eq,"", {:checked => true} %>指定なし
  <%= f.radio_button :status_eq, 1 %>飲酒
  <%= f.radio_button :status_eq, 2 %>未飲酒
  </div>

  <div class="submit">
  <%= f.submit '検索' %>
  </div>
  </div>
<% end %>

<%= link_to "前月", index_admin_user_path(month: @month.prev_month) %>
<%= link_to "翌月", index_admin_user_path(month: @month.next_month) %>

<table class="osare3-table col4t">
  <thead>
    <tr>
      <th></th>
      <th>運転日時</th>
      <th>飲酒</th>
      <th>飲酒日時</th>
      <th>運転可能</th>
      <th>目視</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drinkings.each do |drinking| %>
      <tr>
        <td>
          <% if (drinking.time - drinking.driving_start_time).to_i > 0 %>
            <%= "警告" %>
          <% end %>
          <% drinking.visuallies.each do |visually| %>
            <% if (drinking.driving_start_time - Time.now).to_i > 0 and visually.visually == "未確認" %>
              <%= "確認" %>
            <% end %>
          <% end %>    
        </td>
        <td><%= drinking.driving_start_time.strftime("%m/%d %H:%M") %></td>
        <td><%= link_to drinking.status, drinking_path(drinking) %></td>
        <td>
        <% if drinking.status == "〇" %>
        <%= drinking.drinking_end_time.strftime("%m/%d %H:%M") %>
        <% end %></td>
        <td>
        <% if (drinking.time - Time.now).to_i >= 0 %>
          <%= drinking.time.strftime("%m/%d %H:%M") %>
        <% else %>
          <%= "〇" %>
        <% end %>
        </td>
        <td><% drinking.visuallies.each do |visually| %>
          <%= link_to visually.visually, edit_visually_path(visually) %>
        <% end %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
</section>

app/views/drinkings/new.html.erb
<section class="section">
<div class ="section_inner">
<h1>飲酒記録登録</h1>
  
<%= form_with(model: @drinking, local: true) do |form| %>
  <% if @drinking.errors.any? %>
  <div id="error_explanation">
    <h2>エラーが発生しました。</h2>

    <ul>
      <% @drinking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

    <div class="field">
      <%= form.label :運転日時 %>
      <%= form.datetime_select :driving_start_time %>
    </div>
  
    <div class="field", id="status">
      <span class="status">飲酒状況</span><br>
      <div class ="radio-btn">
      <div class="radio-inline">
        <%= form.label :飲酒, class: "label" %>
        <%= form.radio_button :status, :〇, class: "btn", id: "alcohol_btn" %>
      </div>
      <div class="radio-inline">
        <%= form.label :未飲酒, class: "label" %>
        <%= form.radio_button :status, :× , class: "btn", id: "non_alcohol_btn", checked: "checked" %>
      </div>
      </div>
   </div>
    
    <div id="alcohol_format" style="display: none;">
    <div class="field">
      <%= form.label :飲酒日時 %>
      <%= form.datetime_select :drinking_end_time %>
    </div>
  
    <hr color="#f5b771">

    <div id="alcohol_forms">
    <%= form.fields_for :alcohols do |alcohol| %>
      <% render 'alcohol', alcohol: alcohol %>
    <% end %>
    </div>
    <%= link_to_add_association '+お酒入力フォーム追加', form, :alcohols, partial: "alcohol", data: {association_insertion_node: '#alcohol_forms', association_insertion_method: 'after'}, form_name: 'alcohol' %>
    </div>
    
    <div id="visually_forms">
    <%= form.fields_for :visuallies do |visually| %>
      <%= visually.hidden_field :visually, :value => "未確認" %>
    <% end %>
    </div>
    
    <div class="actions">
      <%= form.submit "登録" %>
    </div>
  <% end %>
  
  <script>
    var element1 = document.getElementById("alcohol_btn");
    var element2 = document.getElementById("non_alcohol_btn");
  
    element1.addEventListener('click', function() {
      document.getElementById('alcohol_format').style.display = "";
    })
  
    element2.addEventListener('click', function() {
      document.getElementById('alcohol_format').style.display = "none";
    })
  </script>
  </div>
  </section>

app/views/drinkings/show.html.erb
<section class="section">
<div class ="section_inner">
<h1>飲酒記録確認</h1>

<table class="osare3-table col4t show">
<tr>
  <td><strong>運転日時</strong></td>
  <td><%= @drinking.driving_start_time.strftime("%m/%d %H:%M") %></td>
</tr>


<tr>
  <td><strong>飲酒状況</strong></td>
  <td>
  <% if @drinking.status == "〇" %>
  <%= "飲酒" %>
  <% else %>
  <%= "未飲酒" %>
  <% end %>
  </td>
</th>

<% if @drinking.status == "〇" %>

<tr>
  <td><strong>飲酒日時</strong></td>
  <td><%= @drinking.drinking_end_time.strftime("%m/%d %H:%M") %></td>
</tr>

<tr>
  <td><strong>運転可能時間</strong></td>
  <td><%= @drinking.time.strftime("%m/%d %H:%M") %></td>
</tr>

<tr>
  <td><strong>純アルコール量</strong></td>
  <td><%= @drinking.total_alcohol.round(2) %>g　※一日の適正量は20gです。
  </td>
</tr>
</table>


<tr>
  <td><strong>詳細</strong></td>
</tr>

  <hr color="#f5b771">

  <table class="osare3-table col4t show detail">
  <thead>
    <tr>
      <th>種類</th>
      <th>度数</th>
      <th>量（ml）</th>
      <th>本数</th>
    </tr>
  </thead>

  <tbody>
  <% @drinking.alcohols.each do |alcohol| %>
    <tr>
    <td><%= alcohol.kind %></td>
    <td><%= alcohol.frequency %></td>
    <td><%= alcohol.quantity %></td>
    <td><%= alcohol.number %></td>
    <tr>
  <% end %>
  </tbody>
  </table>

<% end %>

<%  unless user_admin? %>
<%= link_to '編集', edit_drinking_path(@drinking) %> 
<% end %>
</div>
</section>