config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'drinkings#index'
  get  "drinkings/index_admin_user/:id"  => "drinkings#index_admin_user", as:"index_admin_user"


  resources :drinkings do
    collection do
      get :calculation 
      get :index_admin_day
    end
  end

  resources :visuallies
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimerApp2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class = "header">
        <div class = "log">
          <h3>アルポリ</h3>
        </div>
        <div class="global_nav">
          <nav class="nav">
            <ul class = "nav">
              <% if logged_in? %>
                <% if user_admin? %>
                  <div class = "nav_item">
                    <li><%= link_to "飲酒記録管理", index_admin_day_drinkings_path %></li>
                  </div>
                <% end %>
                <div class = "nav_item">
                  <li><%= link_to "飲酒記録", drinkings_path(current_user.id) %></li>
                </div>
                <div class = "nav_item">
                  <li><%= link_to "飲酒量計算", calculation_drinkings_path(current_user.id) %></li>
                </div>
                <div class = "nav_item">
                  <li><%= link_to "アカウント", user_path(current_user.id) %></li>
                </div>
                <div class = "nav_item">
                  <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
                </div>
              <% else %>
                <div class = "nav_item">
                  <li><%= link_to "アカウント登録", new_user_path %></li>
                </div>
                <div class = "nav_item">
                  <li><%= link_to "ログイン", new_session_path %></li>
                </div>
              <% end %>
            </ul>
          </nav>
          <nav class="nav_toggle">
          <i></i>
            <i></i>
            <i></i>
          </nav>
      </div>
      </div>
    </header>

    <%= yield %>

    <footer>
    <nav>
      <ul class = "footer_item">
        <% if logged_in? %>
          <% if user_admin? %>
            <div class = "footer_nav_item">
              <li><%= link_to "飲酒記録管理", index_admin_day_drinkings_path %></li>
            </div>
          <% end %>
          <div class = "footer_nav_item">
            <li><%= link_to "飲酒記録", drinkings_path(current_user.id) %></li>
          </div>
          <div class = "footer_nav_item">
            <li><%= link_to "飲酒量計算", calculation_drinkings_path(current_user.id) %></li>
          </div>
        <% end %>
        <div class = "footer_nav_item">
          <li><h4>アルポリ</h4></li>
        </div>
      </ul>
      <p class ="footer_copy">©haga ryota</p>
    </nav>
  </footer>
  </body>
</html>

<script>
$('.nav_toggle').on('click', function () {
  $('.nav_toggle, .nav').toggleClass('show');
});
</script>